### ISSUE TITLE
(Question) Could you support the exclusive plugin for PetteriM1 Edition?

### ISSUE THREAD

**Issue by JuChanMin** [Superice666/BlocklyNukkit#5]
When I put in the plugins that depend on the blocknukkit and the blocknukkit...

> 2020-08-05 14:18:38.258 [main] INFO  - Enabling EconomyAPI vSCPE-B3
> 2020-08-05 14:18:38.283 [main] INFO  - Enabling FakeInventories v1.0.3
> 2020-08-05 14:18:38.288 [main] INFO  - Enabling KotlinLib v1.0
> 2020-08-05 14:18:38.290 [main] INFO  - Enabling PlaceholderAPI v1.3.3
> 2020-08-05 14:18:38.291 [main] INFO  - Enabling ScoreboardPlugin v1.0
> 2020-08-05 14:18:38.292 [main] INFO  - Enabling BlocklyNukkit v1.2.8.2
> 2020-08-05 14:18:38.302 [main] ERROR - Throwing
> java.lang.RuntimeException: java.lang.IncompatibleClassChangeError: class com.blocklynukkit.loader.other.Entities.FloatingText has interface cn.nukkit.entity.mob.EntityMob as super class
>     at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:406) [Nukkit-PM1E.jar:?]
>     at cn.nukkit.Server.enablePlugin(Server.java:787) [Nukkit-PM1E.jar:?]
>     at cn.nukkit.Server.enablePlugins(Server.java:777) [Nukkit-PM1E.jar:?]
>     at cn.nukkit.Server.<init>(Server.java:482) [Nukkit-PM1E.jar:?]
>     at cn.nukkit.Nukkit.main(Nukkit.java:78) [Nukkit-PM1E.jar:?]
> Caused by: java.lang.IncompatibleClassChangeError: class com.blocklynukkit.loader.other.Entities.FloatingText has interface cn.nukkit.entity.mob.EntityMob as super class
>     at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_241]
>     at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
> at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
>     at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
>     at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_241]
>     at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_241]
>     at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_241]
>     at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_241]
>     at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
>     at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:43) ~[Nukkit-PM1E.jar:?]
>     at cn.nukkit.plugin.JavaPluginLoader.getClassByName(JavaPluginLoader.java:144) ~[Nukkit-PM1E.jar:?]
>     at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:39) ~[Nukkit-PM1E.jar:?]
>     at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:27) ~[Nukkit-PM1E.jar:?]
>     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
>     at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
>     at com.blocklynukkit.loader.Loader.onEnable(Loader.java:126) ~[?:?]
>     at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[Nukkit-PM1E.jar:?]
>     at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:116) ~[Nukkit-PM1E.jar:?]
>     at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:402) ~[Nukkit-PM1E.jar:?]
>     ... 4 more
> 2020-08-05 14:18:38.310 [main] INFO  - Disabling BlocklyNukkit v1.2.8.2
> 2020-08-05 14:18:38.314 [main] ERROR - Throwing
> java.lang.NullPointerException: null
> at com.blocklynukkit.loader.Loader.onDisable(Loader.java:240) ~[?:?]
>     at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91) ~[Nukkit-PM1E.jar:?]
>     at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:131) ~[Nukkit-PM1E.jar:?]
>     at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:477) [Nukkit-PM1E.jar:?]
>     at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:408) [Nukkit-PM1E.jar:?]
>     at cn.nukkit.Server.enablePlugin(Server.java:787) [Nukkit-PM1E.jar:?]
>     at cn.nukkit.Server.enablePlugins(Server.java:777) [Nukkit-PM1E.jar:?]
>     at cn.nukkit.Server.<init>(Server.java:482) [Nukkit-PM1E.jar:?]
>     at cn.nukkit.Nukkit.main(Nukkit.java:78) [Nukkit-PM1E.jar:?]
> 2020-08-05 14:18:38.344 [main] INFO  - Done (2.59s)! For help, type "help"

The console outputs this error :c
Could you support BlockNukit for PetteriM1 Edition?

(My English is the worst, and this article is being written through a translator.
If you have any unpleasant expressions, I apologize. Xd)

**Comment by SuperIceCN** [comment]
啊这......国人何苦为难国人，中文就好了......
这个兼容工作已经在进行了，由于blocklynukkit架构跟nukkitx咬合得很死，所以去适配petterM1版本相当于重写半个nukkitx了，工作量巨大，加之这玩意主要是由我一个人在空闲休息时间做，还要保证中央数据服务器的维护，还有更新等等，所以这项工作需要比较长的一段时间。感谢您的支持，我会一直努力的。

**Comment by JuChanMin** [comment]
I saw at the NukkitX Forum that you are a student.
Thank you for making a great plugin, and thank you for investing your time. :)
