### ISSUE TITLE
JS 不能使用 对象和类

### ISSUE THREAD

**Issue by Enaium** [Superice666/BlocklyNukkit#8]
对象

![0ATEWt.png](https://s1.ax1x.com/2020/09/28/0ATEWt.png)

类

![0ATZSP.png](https://s1.ax1x.com/2020/09/28/0ATZSP.png)

**Comment by SuperIceCN** [comment]
请将您的代码贴一下谢谢啦

**Comment by Enaium** [comment]
```js
var tpa = {
	play1:"",
	play2:""
}
```

**Comment by SuperIceCN** [comment]
这一段应该不会报错，您可能把声明对象和声明类混淆了
