### ISSUE TITLE
求展示框显示图片

### ISSUE THREAD

**Issue by affov** [Superice666/BlocklyNukkit#9]
许多展示框的排列合成一张大的图片

**Comment by SuperIceCN** [comment]
@affov 请说明一下详细的api内容和实现目标，模板如下：
- API类型: `基对象/函数/事件/语言`
- API名称: `英文对象名/事件名/函数名/语言名`
- API内容: `对象的成员/事件触发条件/函数参数`
- API目标: `实现的结果描述(最好加上代码或图片描述)`

**Comment by affov** [comment]
api类型:world
api名称:drawpic
api内容:drawpic(pos1,pos2,img,callback)
api目标:定义一个从pos1到pos2的画布并显示img图片内容

**Comment by SuperIceCN** [comment]
@affov 已经完成此api，详见https://github.com/Superice666/BlocklyNukkit/releases/tag/v1.2.9.0-beta-r27
